name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Trivy analysis
        run: |
         docker run --rm -v .:/temp aquasec/trivy fs --scanners vuln temp --dependency-tree --format sarif -o temp/report-trivy-backend.sarif
    
