name: Trivy
on: [push]

jobs:
  build:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Archive trivy results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: trivy-results.sarif
